[2021-01-15 16:38:03,371] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: noti_test.op3 2021-01-15T07:35:03.242575+00:00 [queued]>
[2021-01-15 16:38:03,380] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: noti_test.op3 2021-01-15T07:35:03.242575+00:00 [queued]>
[2021-01-15 16:38:03,381] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2021-01-15 16:38:03,381] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2021-01-15 16:38:03,381] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2021-01-15 16:38:03,386] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): op3> on 2021-01-15T07:35:03.242575+00:00
[2021-01-15 16:38:03,388] {standard_task_runner.py:54} INFO - Started process 9201 to run task
[2021-01-15 16:38:03,435] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'noti_test', 'op3', '2021-01-15T07:35:03.242575+00:00', '--job_id', '57', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/noti_test.py', '--cfg_path', '/var/folders/4f/xnn880bn51d9945mdydbgwdw0000gn/T/tmp47lpp8ph']
[2021-01-15 16:38:03,436] {standard_task_runner.py:78} INFO - Job 57: Subtask op3
[2021-01-15 16:38:03,455] {logging_mixin.py:112} INFO - Running <TaskInstance: noti_test.op3 2021-01-15T07:35:03.242575+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2021-01-15 16:38:03,467] {logging_mixin.py:112} INFO - function3
[2021-01-15 16:38:03,467] {python_operator.py:114} INFO - Done. Returned value was: None
[2021-01-15 16:38:03,469] {taskinstance.py:1052} ERROR - Failed when executing success callback
[2021-01-15 16:38:03,470] {taskinstance.py:1053} ERROR - unsupported operand type(s) for +: 'set' and 'str'
Traceback (most recent call last):
  File "/Users/ichiro/.pyenv/versions/3.9.1/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1050, in _run_raw_task
    task.on_success_callback(context)
  File "/Users/ichiro/airflow/dags/noti_test.py", line 44, in successed
    'text': {dag_name}+'was successed!'
TypeError: unsupported operand type(s) for +: 'set' and 'str'
[2021-01-15 16:38:03,474] {taskinstance.py:1057} INFO - Marking task as SUCCESS.dag_id=noti_test, task_id=op3, execution_date=20210115T073503, start_date=20210115T073803, end_date=20210115T073803
[2021-01-15 16:38:08,374] {local_task_job.py:102} INFO - Task exited with return code 0
